# Essential Pytorch .....

In [1]:
import torch
import numpy as np
print(f"PyTorch version: {torch.__version__}")

PyTorch version: 2.5.1+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


### Creating a tensor

In [3]:
# 1. Initialize an uninitialized tensor of size 2x3
input_tensor = torch.empty(2,3)
# 2. Print the content of the tensor to the console
print(input_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# 1. Retrieve the class type of the input_tensor object
type(input_tensor)

torch.Tensor

In [5]:
# Zeros tensor
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Ones tensor
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# Random tensor
torch.rand(2,3)

tensor([[0.7150, 0.9481, 0.5035],
        [0.0284, 0.4840, 0.2974]])

In [8]:
# Manual Seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [9]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# Other ways to create tensor

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [11]:
# 1. Manually define a 2D tensor with specific integer values
input_tensor = torch.tensor([[1,2,3],[4,5,6]])

In [12]:
# 1. Access the shape attribute of the input_tensor to see dimensions
input_tensor.shape

torch.Size([2, 3])

In [13]:
# 1. Create a new uninitialized tensor with the same shape as input_tensor
torch.empty_like(input_tensor)

tensor([[140536944016368, 140536944016368,               0],
        [            193,      1182333808, 140536944016160]])

In [14]:
# 1. Create a new tensor of zeros with the same shape as input_tensor
torch.zeros_like(input_tensor)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
# 1. Create a new tensor of ones with the same shape as input_tensor
torch.ones_like(input_tensor)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])

### Tensor Data Type

In [ ]:
# 1. Inspect the underlying data type (e.g., int64) of input_tensor
input_tensor.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# 1. Cast the input_tensor to a 32-bit floating point format
input_tensor.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operation


In [ ]:
# 1. Generate a 3x3 tensor filled with random numbers between 0 and 1
x = torch.rand(3,3)
print(x)

tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])


In [ ]:
# 1. Output the current content of variable x to the console
x

tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])

In [ ]:
# 1. Perform scalar addition by adding 2 to every element in tensor x
x + 2

tensor([[2.4294, 2.8854, 2.5739],
        [2.2666, 2.6274, 2.2696],
        [2.4414, 2.2969, 2.8317]])

In [ ]:
# 1. Perform scalar subtraction by subtracting 2 from every element in tensor x
x - 2

tensor([[-1.5706, -1.1146, -1.4261],
        [-1.7334, -1.3726, -1.7304],
        [-1.5586, -1.7031, -1.1683]])

In [ ]:
# 1. Perform scalar multiplication by doubling every element in tensor x
x * 2

tensor([[0.8588, 1.7709, 1.1478],
        [0.5332, 1.2549, 0.5393],
        [0.8827, 0.5938, 1.6634]])

In [ ]:
# 1. Perform scalar division by dividing every element in tensor x by 2
x / 2

tensor([[0.2147, 0.4427, 0.2870],
        [0.1333, 0.3137, 0.1348],
        [0.2207, 0.1485, 0.4158]])

In [ ]:
# 1. Multiply x by 10, then perform integer (floor) division by 3
x * 10 // 3

tensor([[1., 2., 1.],
        [0., 2., 0.],
        [1., 0., 2.]])

In [ ]:
# 1. Raise every element in tensor x to the power of 2
x ** 2

tensor([[0.1844, 0.7840, 0.3294],
        [0.0711, 0.3937, 0.0727],
        [0.1948, 0.0882, 0.6917]])

### Element wise operation

In [ ]:
# 1. Create a 2x3 random tensor named 'a'
a = torch.rand(2,3)
# 2. Create another 2x3 random tensor named 'b'
b = torch.rand(2,3)
# 3. Display the first tensor 'a'
print(a)
# 4. Display the second tensor 'b'
print(b)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])
tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])


In [ ]:
# 1. Add tensor a and b element-wise
print(a + b)
# 2. Subtract tensor b from a element-wise
print(a - b)
# 3. Multiply tensor a and b element-wise
print(a * b)
# 4. Divide tensor a by b element-wise
print(a / b)
# 5. Raise tensor a to the power of elements in b
print(a ** b)
# 6. Calculate the remainder of a divided by b (modulo)
print(a % b)

tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]])
tensor([[-0.8462,  0.1942, -0.5272],
        [-0.3838,  0.2095, -0.8028]])
tensor([[0.1002, 0.0203, 0.3179],
        [0.1163, 0.1848, 0.0050]])
tensor([[0.1107, 3.5806, 0.4050],
        [0.3418, 1.6206, 0.0076]])
tensor([[0.1174, 0.9060, 0.4033],
        [0.3904, 0.8158, 0.0163]])
tensor([[0.1053, 0.0437, 0.3588],
        [0.1994, 0.2095, 0.0062]])


In [ ]:
# 1. Create a 1D tensor with mixed positive and negative integers
signed_tensor = torch.tensor([1, -2, 3, -4])
print(signed_tensor)

tensor([ 1, -2,  3, -4])


In [ ]:
# 1. Calculate the absolute value of each element in signed_tensor
torch.abs(signed_tensor)

tensor([1, 2, 3, 4])

In [ ]:
# 1. Negate each element in the signed_tensor
torch.neg(signed_tensor)

tensor([-1,  2, -3,  4])

In [ ]:
# 1. Create a 1D tensor with decimal values for rounding tests
float_tensor = torch.tensor([1.9, 2.3, 3.7, 4.4])
print(float_tensor)

tensor([1.9000, 2.3000, 3.7000, 4.4000])


In [ ]:
# 1. Round each element in float_tensor to the nearest integer
torch.round(float_tensor)

tensor([2., 2., 4., 4.])

In [ ]:
# 1. Round each element in float_tensor up to the nearest integer (ceil)
torch.ceil(float_tensor)

tensor([2., 3., 4., 5.])

In [ ]:
# 1. Round each element in float_tensor down to the nearest integer (floor)
torch.floor(float_tensor)

tensor([1., 2., 3., 4.])

In [ ]:
# 1. Constrain elements in float_tensor to be between 2 and 3
torch.clamp(float_tensor, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### Reduction operation

In [ ]:
# 1. Create a 2x3 tensor of random integers between 0 and 10
# 2. Set the data type to float32 to allow for reduction operations like mean
reduction_tensor = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
# 3. Display the generated tensor
print(reduction_tensor)

tensor([[9., 6., 2.],
        [0., 6., 2.]])


In [ ]:
# 1. Calculate the sum of all elements in the tensor
print(torch.sum(reduction_tensor))
# 2. Calculate the sum along columns (dimension 0)
print(torch.sum(reduction_tensor, dim=0))
# 3. Calculate the sum along rows (dimension 1)
print(torch.sum(reduction_tensor, dim=1))

tensor(25.)
tensor([ 9., 12.,  4.])
tensor([17.,  8.])


In [ ]:
# 1. Calculate the average of all elements in the tensor
print(torch.mean(reduction_tensor))
# 2. Calculate the average along columns (dimension 0)
print(torch.mean(reduction_tensor, dim=0))

tensor(4.1667)
tensor([4.5000, 6.0000, 2.0000])


In [ ]:
# 1. Find the median value among all elements in the reduction_tensor
torch.median(reduction_tensor)

tensor(2.)

In [ ]:
# 1. Find the maximum value in the tensor
print(torch.max(reduction_tensor))
# 2. Find the minimum value in the tensor
print(torch.min(reduction_tensor))

tensor(9.)
tensor(0.)


In [ ]:
# 1. Calculate the product of all elements in the tensor multiplied together
torch.prod(reduction_tensor)

tensor(0.)

In [ ]:
# 1. Calculate the standard deviation of the elements in the tensor
torch.std(reduction_tensor)

tensor(3.3714)

In [ ]:
# 1. Calculate the variance of the elements in the tensor
torch.var(reduction_tensor)

tensor(11.3667)

In [ ]:
# 1. Find the index of the maximum value in the flattened tensor
torch.argmax(reduction_tensor)

tensor(0)

In [ ]:
# 1. Find the index of the minimum value in the flattened tensor
torch.argmin(reduction_tensor)

tensor(3)

### Matrix operations

In [ ]:
# 1. Create a 2x3 integer tensor named 'matrix_a'
matrix_a = torch.randint(size=(2,3), low=0, high=10)
# 2. Create a 3x2 integer tensor named 'matrix_b'
matrix_b = torch.randint(size=(3,2), low=0, high=10)
# 3. Print matrix_a
print(matrix_a)
# 4. Print matrix_b
print(matrix_b)

tensor([[7, 9, 7],
        [3, 3, 4]])
tensor([[3, 7],
        [0, 9],
        [0, 9]])


In [ ]:
# 1. Perform matrix multiplication (dot product) between matrix_a and matrix_b
torch.matmul(matrix_a, matrix_b)

tensor([[ 21, 193],
        [  9,  84]])

In [ ]:
# 1. Define the first 1D vector
vector1 = torch.tensor([1, 2])
# 2. Define the second 1D vector
vector2 = torch.tensor([3, 4])
# 3. Compute the dot product of the two vectors
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# 1. Swap the dimensions (transpose) of matrix_a
torch.transpose(matrix_a, 0, 1)

tensor([[7, 3],
        [9, 3],
        [7, 4]])

In [ ]:
# 1. Create a 3x3 square matrix with random values for linear algebra tests
square_matrix = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
# 2. Display the matrix
square_matrix

tensor([[6., 9., 5.],
        [4., 8., 8.],
        [6., 0., 0.]])

In [ ]:
# 1. Compute the determinant of the square_matrix
torch.det(square_matrix)

tensor(192.0000)

In [ ]:
# 1. Compute the multiplicative inverse of the square_matrix
torch.inverse(square_matrix)

tensor([[ 0.0000,  0.0000,  0.1667],
        [ 0.2500, -0.1563, -0.1458],
        [-0.2500,  0.2813,  0.0625]])

### Comparison operations

In [ ]:
# 1. Create a 2x3 tensor of random integers from 0 to 10 named 'tensor_i'
tensor_i = torch.randint(size=(2,3), low=0, high=10)
# 2. Create a 2x3 tensor of random integers from 0 to 10 named 'tensor_j'
tensor_j = torch.randint(size=(2,3), low=0, high=10)
# 3. Print the content of tensor_i
print(tensor_i)
# 4. Print the content of tensor_j
print(tensor_j)

tensor([[0, 0, 1],
        [3, 0, 1]])
tensor([[1, 7, 9],
        [4, 3, 8]])


In [ ]:
# 1. Check if elements in tensor_i are greater than tensor_j
print(tensor_i > tensor_j)
# 2. Check if elements in tensor_i are less than tensor_j
print(tensor_i < tensor_j)
# 3. Check if elements in tensor_i are equal to tensor_j
print(tensor_i == tensor_j)
# 4. Check if elements in tensor_i are not equal to tensor_j
print(tensor_i != tensor_j)

tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


### Special functions

In [ ]:
# 1. Create a 2x3 random integer tensor with float32 type for activation functions
activation_input = torch.randint(size=(2,3), low=1, high=10, dtype=torch.float32)
# 2. Display the input tensor
print(activation_input)

tensor([[3., 4., 2.],
        [9., 6., 7.]])


In [ ]:
# 1. Calculate the natural logarithm (log base e) of each element in activation_input
torch.log(activation_input)

tensor([[1.0986, 1.3863, 0.6931],
        [2.1972, 1.7918, 1.9459]])

In [ ]:
# 1. Calculate the exponential (e^x) of each element in activation_input
torch.exp(activation_input)

tensor([[2.0086e+01, 5.4598e+01, 7.3891e+00],
        [8.1031e+03, 4.0343e+02, 1.0966e+03]])

In [ ]:
# 1. Calculate the square root of each element in activation_input
torch.sqrt(activation_input)

tensor([[1.7321, 2.0000, 1.4142],
        [3.0000, 2.4495, 2.6458]])

In [ ]:
# 1. Apply the sigmoid activation function element-wise
torch.sigmoid(activation_input)

tensor([[0.9526, 0.9820, 0.8808],
        [0.9999, 0.9975, 0.9991]])

In [ ]:
# 1. Apply the softmax function along the columns (dimension 0)
torch.softmax(activation_input, dim=0)

tensor([[0.0025, 0.1192, 0.0067],
        [0.9975, 0.8808, 0.9933]])

In [ ]:
# 1. Apply the Rectified Linear Unit (ReLU) activation function
torch.relu(activation_input)

tensor([[3., 4., 2.],
        [9., 6., 7.]])

### Inplace Operations

In [ ]:
# 1. Create a 2x3 random tensor named 'tensor_m'
tensor_m = torch.rand(2,3)
# 2. Create another 2x3 random tensor named 'tensor_n'
tensor_n = torch.rand(2,3)
# 3. Print the first tensor
print(tensor_m)
# 4. Print the second tensor
print(tensor_n)

tensor([[0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])
tensor([[0.1115, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])


In [ ]:
# 1. Perform an inplace addition: add tensor_n to tensor_m and update tensor_m
tensor_m.add_(tensor_n)

tensor([[0.2707, 1.0130, 0.9503],
        [1.4092, 0.7539, 1.5841]])

In [ ]:
# 1. Display the current content of tensor_m to verify the inplace addition result
tensor_m

tensor([[0.2707, 1.0130, 0.9503],
        [1.4092, 0.7539, 1.5841]])

In [ ]:
# 1. Display the current content of tensor_n
tensor_n

tensor([[0.1115, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

In [ ]:
# 1. Apply ReLU activation to tensor_m (returns a new tensor)
torch.relu(tensor_m)

tensor([[0.2707, 1.0130, 0.9503],
        [1.4092, 0.7539, 1.5841]])

In [ ]:
# 1. Apply ReLU activation to tensor m inplace (modifies m directly)
m.relu_()

NameError: name 'm' is not defined

In [ ]:
# 1. Print tensor m to show it was modified by the previous inplace ReLU operation
m

### Copying a Tensor

In [ ]:
# 1. Create a 2x3 random tensor named 'original_tensor'
original_tensor = torch.rand(2,3)
# 2. Display the original tensor
print(original_tensor)

In [ ]:
# 1. Create a shallow copy (reference) by assignment
shallow_copy = original_tensor

In [ ]:
# 1. Display the content of shallow_copy to show it references the same data as original_tensor
shallow_copy

tensor([[0.9546, 0.2330, 0.7885],
        [0.9318, 0.0457, 0.2733]])

In [ ]:
# 1. Modify the first element of original_tensor to 0
original_tensor[0][0] = 0

In [ ]:
# 1. Display original_tensor after modification
original_tensor

tensor([[0.0000, 0.2330, 0.7885],
        [0.9318, 0.0457, 0.2733]])

In [ ]:
# 1. Display shallow_copy to demonstrate that changing original_tensor also changed shallow_copy
shallow_copy

tensor([[0.0000, 0.2330, 0.7885],
        [0.9318, 0.0457, 0.2733]])

In [ ]:
# 1. Get the unique memory address (ID) of original_tensor
id(original_tensor)

133549204247312

In [ ]:
# 1. Get the unique memory address (ID) of shallow_copy to compare with original_tensor
id(shallow_copy)

133549204247312

In [ ]:
# 1. Create a deep copy of the tensor using the clone method
deep_copy = original_tensor.clone()

In [ ]:
# 1. Check content of original_tensor before further changes
original_tensor

tensor([[0.0000, 0.2330, 0.7885],
        [0.9318, 0.0457, 0.2733]])

In [ ]:
# 1. Check content of deep_copy before further changes
deep_copy

tensor([[0.9546, 0.2330, 0.7885],
        [0.9318, 0.0457, 0.2733]])

In [ ]:
# 1. Change the first element of original_tensor to 10
original_tensor[0][0] = 10

In [ ]:
# 1. Verify original_tensor reflects the new change
original_tensor

tensor([[10.0000,  0.2330,  0.7885],
        [ 0.9318,  0.0457,  0.2733]])

In [ ]:
# 1. Verify deep_copy remains unchanged (it is a deep copy via .clone())
deep_copy

tensor([[0.9546, 0.2330, 0.7885],
        [0.9318, 0.0457, 0.2733]])

In [ ]:
# 1. Check memory ID of original_tensor again
id(original_tensor)

133549204247312

In [ ]:
# 1. Check memory ID of deep_copy to show it is different from original_tensor
id(deep_copy)

133549204354256

### Tensor Operations on GPU

In [ ]:
# 1. Verify if the system has a GPU available for PyTorch
torch.cuda.is_available()

True

In [ ]:
# 1. Define the target device as the GPU (CUDA)
target_device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
target_device

device(type='cuda')

In [ ]:
# 1. Directly create a new random 2x3 tensor on the specified GPU device
torch.rand((2,3), device=target_device)

tensor([[0.9877, 0.1289, 0.5621],
        [0.5221, 0.7445, 0.5955]], device='cuda:0')

In [ ]:
# 1. Display the content of tensor 'a' currently on the CPU
a

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])

In [ ]:
# 1. Move the 'original_tensor' from CPU memory to the specified GPU device
gpu_tensor = original_tensor.to(target_device)

In [ ]:
# 1. Display the content of tensor 'b' currently on the CPU
b

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])

In [ ]:
import time
import torch

# 1. Define the size of the square matrices for benchmarking
matrix_dimension = 10000

# 2. Initialize two large random matrices on the CPU
matrix_cpu_a = torch.randn(matrix_dimension, matrix_dimension)
matrix_cpu_b = torch.randn(matrix_dimension, matrix_dimension)

# 3. Measure matrix multiplication execution time on the CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu_a, matrix_cpu_b)
cpu_duration = time.time() - start_time

print(f"Time on CPU: {cpu_duration:.4f} seconds")

# 4. If CUDA is available, transfer matrices to GPU and measure performance
if torch.cuda.is_available():
    matrix_gpu_a = matrix_cpu_a.to('cuda')
    matrix_gpu_b = matrix_cpu_b.to('cuda')

    # Measure matrix multiplication execution time on the GPU
    start_time = time.time()
    result_gpu = torch.matmul(matrix_gpu_a, matrix_gpu_b)
    torch.cuda.synchronize()  # Wait for GPU computation to finish
    gpu_duration = time.time() - start_time

    print(f"Time on GPU: {gpu_duration:.4f} seconds")
    # 5. Calculate and display the speedup factor
    print("\nSpeedup (CPU time / GPU time):", cpu_duration / gpu_duration)
else:
    print("CUDA is not available on this system.")

Time on CPU: 16.1281 seconds
Time on GPU: 0.5437 seconds

Speedup (CPU time / GPU time): 29.662084448741645


### Reshaping tensor

In [ ]:
# 1. Create a 4x4 tensor filled with ones
reshape_target = torch.ones(4,4)

In [ ]:
# 1. Display the 4x4 ones tensor
a

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])

In [ ]:
# 1. Change the dimensions of the tensor to a 4D structure (2x2x2x2)
reshape_target.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# 1. Collapse all dimensions of the tensor into a single 1D vector
reshape_target.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# 1. Create a 3D random tensor with dimensions 2x3x4
b_reshape = torch.rand(2,3,4)

In [ ]:
# 1. Display the 3D tensor b
b

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])

In [ ]:
# 1. Reorder dimensions of b_reshape from (0,1,2) to (2,0,1)
b_reshape.permute(2,0,1)

tensor([[[0.8445, 0.5084, 0.8910],
         [0.9721, 0.3085, 0.7077]],

        [[0.7442, 0.7062, 0.4351],
         [0.1496, 0.5943, 0.4368]],

        [[0.3196, 0.5106, 0.3931],
         [0.4022, 0.2009, 0.4211]],

        [[0.8934, 0.4133, 0.5704],
         [0.8337, 0.2635, 0.0035]]])

In [ ]:
# 1. Create a 3D tensor simulating an image (Height, Width, Channels)
c = torch.rand(226,226,3)

In [ ]:
# 1. Display the 3D 'image' tensor
c

tensor([[[0.9861, 0.0194, 0.4335],
         [0.9664, 0.3780, 0.8451],
         [0.1779, 0.6300, 0.8525],
         ...,
         [0.5622, 0.4739, 0.5687],
         [0.3873, 0.4440, 0.1875],
         [0.8993, 0.9106, 0.3574]],

        [[0.3160, 0.1864, 0.2245],
         [0.9670, 0.5924, 0.9577],
         [0.9575, 0.9631, 0.0027],
         ...,
         [0.2518, 0.3199, 0.5177],
         [0.8085, 0.9050, 0.0063],
         [0.8493, 0.7377, 0.0041]],

        [[0.6688, 0.2292, 0.6267],
         [0.1277, 0.6710, 0.1332],
         [0.5543, 0.0985, 0.6797],
         ...,
         [0.9884, 0.8831, 0.0943],
         [0.2240, 0.1651, 0.7418],
         [0.9412, 0.9327, 0.5105]],

        ...,

        [[0.3914, 0.1933, 0.6393],
         [0.3229, 0.6318, 0.1235],
         [0.9189, 0.1978, 0.9364],
         ...,
         [0.9233, 0.1614, 0.7623],
         [0.8734, 0.5743, 0.3357],
         [0.0628, 0.1448, 0.4486]],

        [[0.9358, 0.4870, 0.5424],
         [0.8378, 0.5551, 0.7838],
         [0.

In [ ]:
# 1. Add a new leading dimension of size 1 (Batch dimension)
c_image = torch.rand(226,226,3)
c_image.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# 1. Create a 1x20 tensor (2D with a singleton dimension)
d_singleton = torch.rand(1,20)

In [ ]:
# 1. Display the 1x20 tensor
d_singleton

tensor([[0.9661, 0.8230, 0.1680, 0.8319, 0.2651, 0.0783, 0.3884, 0.5620, 0.3354,
         0.7262, 0.6524, 0.1132, 0.6383, 0.4057, 0.7813, 0.3640, 0.0511, 0.8577,
         0.2502, 0.2634]])

### Numpy and PyTorch

In [ ]:
import numpy as np

In [ ]:
# 1. Create a PyTorch tensor from a list of integers
bridge_tensor = torch.tensor([1,2,3])

In [ ]:
# 1. Verify the content of the bridge tensor
a

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])

In [ ]:
# 1. Convert the PyTorch tensor into a NumPy ndarray
numpy_array = bridge_tensor.numpy()

In [ ]:
# 1. Check the Python class type of the resulting numpy object
type(b)

torch.Tensor

In [ ]:
# 1. Create a standard NumPy array
raw_numpy = np.array([1,2,3])

In [ ]:
# 1. Convert the existing NumPy array back into a PyTorch tensor
back_to_torch = torch.from_numpy(raw_numpy)

In [ ]:
# 1. Check the Python class type of the back_to_torch object
type(back_to_torch)

torch.Tensor

In [ ]:
# 1. Display the tensor that was converted back from NumPy
back_to_torch

tensor([1, 2, 3])